In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
from Services.read_data import Dados

In [16]:
file_name = f'Input/Dados.xlsx'

dados = Dados(file_name)

In [27]:
dados.RF.head()

     I    J  K  C  T   RF
0  1.0  1.0  1  1  1  0.0
1  1.0  1.0  1  1  2  0.0
2  1.0  1.0  1  1  3  0.0
3  1.0  1.0  1  1  4  0.0
4  1.0  1.0  1  1  5  0.0

In [35]:
dados.RF[(dados.RF['I'] == 1) & (dados.RF['J'] == 6) & (dados.RF['K'] == 1)]

       I    J  K  C   T          RF
288  1.0  6.0  1  1   1  584.117647
289  1.0  6.0  1  1   2  584.117647
290  1.0  6.0  1  1   3  584.117647
291  1.0  6.0  1  1   4  584.117647
292  1.0  6.0  1  1   5  584.117647
293  1.0  6.0  1  1   6  584.117647
294  1.0  6.0  1  1   7  584.117647
295  1.0  6.0  1  1   8  584.117647
296  1.0  6.0  1  1   9  584.117647
297  1.0  6.0  1  1  10  584.117647
298  1.0  6.0  1  1  11  584.117647
299  1.0  6.0  1  1  12  584.117647
300  1.0  6.0  1  2   1  584.117647
301  1.0  6.0  1  2   2  584.117647
302  1.0  6.0  1  2   3  584.117647
303  1.0  6.0  1  2   4  584.117647
304  1.0  6.0  1  2   5  584.117647
305  1.0  6.0  1  2   6  584.117647
306  1.0  6.0  1  2   7  584.117647
307  1.0  6.0  1  2   8  584.117647
308  1.0  6.0  1  2   9  584.117647
309  1.0  6.0  1  2  10  584.117647
310  1.0  6.0  1  2  11  584.117647
311  1.0  6.0  1  2  12  584.117647

In [31]:
dados.port_nums

array([1., 2., 3., 6., 8.])

In [22]:
dados.De_Para_Portos

     De  Para
0   MAO     1
1   PEC     2
2   SUA     3
3   SSA     4
4   IGI     5
5   SSZ     6
6   IOA     7
7   PNG     8
8   ITJ     9
9   VLC    10
10  SLZ    11
11  VIX    12
12  RIO    13
13  NVT    14
14  IBI    15
15  RIG    16